### PR TITLE
cancel the url encoding decoding special processing of space

### PR DESCRIPTION
**Pull request by HongXG**

### CODE REVIEW

**Comment by zhengshuxin** [comment]
Why cancel encoding/decoding space?

**Comment by HongXG** [comment]
space encoded into "%20", not "+". other programs can't recognize.

**Comment by HongXG** [comment]
other programs can't recognize. space encoded into "%20", not "+".

**Comment by zhengshuxin** [comment]
I've fixed the problem for '+' encoding/decoding.
Thanks.
-zsx

**Pull request closed without merging**
